### Получить всех пользователей
GET http://localhost:5000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMTIzQG1haWwucnUiLCJpZCI6Mywicm9sZXMiOlt7ImlkIjoyLCJ2YWx1ZSI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiLQkNCU0LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMDJUMTA6MDQ6MjAuMDU2WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMDJUMTA6MDQ6MjAuMDU2WiJ9XSwiaWF0IjoxNjY1NDE3MzMyLCJleHAiOjE2NjYwMjIxMzJ9.J9OL9XucHgJ3I_yAkighl7YoqdI7NvmjUDg8yy0EyYU

### Получить пользователя по айди
GET http://localhost:5000/users/5 HTTP/1.1

### Получить депутатов
GET http://localhost:5000/users/deputats HTTP/1.1

### Удалить пользователя по айди
DELETE http://localhost:5000/users/6 HTTP/1.1

### Добавить новую роль
POST http://localhost:5000/roles HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NTg1OTIsImV4cCI6MTY2NjQ1ODYwN30.Whk8KSuRhyJY0qinHMjB2edxBnrX-tlpDb7TOB_z0Ws

{
    "value": "DEPUTAT",
    "description": "Депутат"
}

### Получить роль по названию
http://localhost:5000/roles/USER

### Получить все роли
http://localhost:5000/roles

### Удалить роль
DELETE http://localhost:5000/roles/IOsds HTTP/1.1

### Логин
POST http://localhost:5000/auth/login
content-type: application/json

{
	"email": "admin@mail.ru",
    "password": "12345"
}

### Регистрация
POST http://localhost:5000/auth/registration
content-type: application/json

{
	"email": "deputat1235@mail.ru",
    "password": "12345",
    "first_name": "Сява",
    "second_name": "Васечкин",
    "father_name": "Петрович"

}

### Редактирование профиля
PATCH http://localhost:5000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlcHV0YXRAbWFpbC5ydSIsImlkIjoyLCJyb2xlcyI6W3siaWQiOjEsInZhbHVlIjoiVVNFUiIsImRlc2NyaXB0aW9uIjoi0J_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQwODozMDowMy40MjRaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQwODozMDowMy40MjRaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjoyLCJyb2xlX2lkIjoxfX1dLCJpYXQiOjE2NzAxMDQxMzYsImV4cCI6MTY3Nzg4MDEzNn0.KumOcg_SOpW_d_Zii_gA9HZOqSbJV-Hvw0Q3fWGcZ_g
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="first_name"

Вася
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="second_name"

Петечекин
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
### Получить юзера по токену
GET http://localhost:5000/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6MSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MSwidXNlcl9pZCI6MSwicm9sZV9pZCI6MX19LHsiaWQiOjgsInZhbHVlIjoiREVQVVRBVCIsImRlc2NyaXB0aW9uIjoi0JTQtdC_0YPRgtCw0YIiLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTIyVDE2OjQyOjQ4LjI2MVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTIyVDE2OjQyOjQ4LjI2MVoiLCJVc2VyUm9sZXMiOnsiaWQiOjIsInVzZXJfaWQiOjEsInJvbGVfaWQiOjh9fSx7ImlkIjoyLCJ2YWx1ZSI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiLQkNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMTk6MDk6MDkuMDI5WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMTk6MDk6MDkuMDI5WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6MSwicm9sZV9pZCI6Mn19XSwiaWF0IjoxNjcwMTAwNTA0LCJleHAiOjE2Nzc4NzY1MDR9.iGQW-IasoD72Av9c2eWAq7jU5WzUHxkfBCuORv-juCg

### Добавить роль
POST http://localhost:5000/users/role HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NTY5MTYsImV4cCI6MTY3NDIzMjkxNn0.og6U6_b8wGEVxVjAROJt_KT4Y3eTiomtcf6hwFVxAcE

{
    "userId": 4,
    "value": "DEPUTAT"
}

### Создать новость
POST http://localhost:5000/news HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NjM1MTksImV4cCI6MTY3NDIzOTUxOX0.SWUpwzUyQN18fGDZrJBzIqcDn_XRc5pP9u6fRxNkaFI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Сто тысяч новостей челендж
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

Айяйяйяй убили негра убили негра....
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Обновить новость
PUT http://localhost:5000/news/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NjM1MTksImV4cCI6MTY3NDIzOTUxOX0.SWUpwzUyQN18fGDZrJBzIqcDn_XRc5pP9u6fRxNkaFI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Сто тысяч но
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

Айяйяйяра убили...
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Получить все новости
GET http://localhost:5000/news?page=3&limit=6 HTTP/1.1

### Получить одну новость
GET http://localhost:5000/news/17 HTTP/1.1

### Удалить одну новость
DELETE http://localhost:5000/news/3 HTTP/1.1

### Получить все обращения
GET http://localhost:5000/requests?page=0&limit=6 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NTY5MTYsImV4cCI6MTY3NDIzMjkxNn0.og6U6_b8wGEVxVjAROJt_KT4Y3eTiomtcf6hwFVxAcE

### Создать обращение
POST http://localhost:5000/requests HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NjM1MTksImV4cCI6MTY3NDIzOTUxOX0.SWUpwzUyQN18fGDZrJBzIqcDn_XRc5pP9u6fRxNkaFI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWykTrZu0gW

------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="title"

Трубы текут
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="text"

уже не можно жить
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="deputat_id"

1
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="files"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="files"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWykTrZu0gW--

### Удалить обращение
DELETE http://localhost:5000/requests/1 HTTP/1.1

### Получить все ответы на обращения
GET http://localhost:5000/requests_answers HTTP/1.1

### Получить оДин ответ
GET http://localhost:5000/requests_answers/3 HTTP/1.1

### Создать ответ на обращение
POST http://localhost:5000/requests_answers/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6MSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MSwidXNlcl9pZCI6MSwicm9sZV9pZCI6MX19LHsiaWQiOjgsInZhbHVlIjoiREVQVVRBVCIsImRlc2NyaXB0aW9uIjoi0JTQtdC_0YPRgtCw0YIiLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTIyVDE2OjQyOjQ4LjI2MVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTIyVDE2OjQyOjQ4LjI2MVoiLCJVc2VyUm9sZXMiOnsiaWQiOjIsInVzZXJfaWQiOjEsInJvbGVfaWQiOjh9fSx7ImlkIjoyLCJ2YWx1ZSI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiLQkNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMTk6MDk6MDkuMDI5WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMTk6MDk6MDkuMDI5WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6MSwicm9sZV9pZCI6Mn19XSwiaWF0IjoxNjcwMTAwNTA0LCJleHAiOjE2Nzc4NzY1MDR9.iGQW-IasoD72Av9c2eWAq7jU5WzUHxkfBCuORv-juCg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWykTrZu0gW

------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="text"

нам пофек ничего чинить не будем
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="frequent"

true
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="files"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWykTrZu0gW
Content-Disposition: form-data; name="files"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWykTrZu0gW--

### Удалить ответ на обращение
DELETE http://localhost:5000/requests_answers/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX0seyJpZCI6OCwidmFsdWUiOiJERVBVVEFUIiwiZGVzY3JpcHRpb24iOiLQlNC10L_Rg9GC0LDRgiIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjJUMTY6NDI6NDguMjYxWiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjJUMTY6NDI6NDguMjYxWiIsIlVzZXJSb2xlcyI6eyJpZCI6OCwidXNlcl9pZCI6NSwicm9sZV9pZCI6OH19XSwiaWF0IjoxNjY5NDY0ODIyLCJleHAiOjE2NzcyNDA4MjJ9.AHbnD7lEPf8M1ylW5dqxWAEsK1sF3VguFu_CC8a1q8M


### Модерировать обращение
PUT http://localhost:5000/requests/moderate/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NTY5MTYsImV4cCI6MTY3NDIzMjkxNn0.og6U6_b8wGEVxVjAROJt_KT4Y3eTiomtcf6hwFVxAcE

{
  "approved": true,
  "moderating_text": "обращенине не проходит"
}


### Забанить пользователя
POST http://localhost:5000/users/ban HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwucnUiLCJpZCI6NSwicm9sZXMiOlt7ImlkIjoxLCJ2YWx1ZSI6IlVTRVIiLCJkZXNjcmlwdGlvbiI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjBUMDg6MzA6MDMuNDI0WiIsIlVzZXJSb2xlcyI6eyJpZCI6MywidXNlcl9pZCI6NSwicm9sZV9pZCI6MX19LHsiaWQiOjIsInZhbHVlIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6ItCQ0LTQvNC40L3QuNGB0YLRgNCw0YLQvtGAIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQxOTowOTowOS4wMjlaIiwiVXNlclJvbGVzIjp7ImlkIjo0LCJ1c2VyX2lkIjo1LCJyb2xlX2lkIjoyfX1dLCJpYXQiOjE2NjY0NTY5MTYsImV4cCI6MTY3NDIzMjkxNn0.og6U6_b8wGEVxVjAROJt_KT4Y3eTiomtcf6hwFVxAcE

{
    "userId": "11",
    "banReason": "134"
}

### Зарегистрироваться
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "email": "admin123@mail.ru",
    "password": "12345"
}

### Авторизоваться
POST http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "admin@mail.ru",
    "password": "123"
}


### Создать пост
POST http://localhost:5000/posts HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

content
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userId"

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--